import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { PersonaDraft, PersonaProfile } from './persona-models';
import { PersonaStore } from './persona-store';

@Component({ selector: 'aura-persona-list-page', standalone: true, imports: [RouterLink], changeDetection: ChangeDetectionStrategy.OnPush, template: `
  <main class="feature-page"><header class="feature-heading"><div><p class="eyebrow">Reusable style</p><h1>Personas</h1><p class="lede">Keep expression separate from an agent's purpose and permissions.</p></div><a class="primary-button" routerLink="/personas/new">Create persona</a></header>@if (store.notice()) { <p class="notice" role="alert">{{ store.notice() }}</p> }@if (store.loading()) { <p class="empty-state" role="status">Loading personas…</p> } @else { <div class="card-grid">@for (persona of store.personas(); track persona.id) { <a class="feature-card" [routerLink]="['/personas', persona.id]"><div class="card-top"><span class="status" [class.disabled]="persona.status === 'disabled'">{{ persona.status }}</span><span class="revision">r{{ persona.revisions.length }}</span></div><h2>{{ persona.displayName }}</h2><p>{{ persona.revisions.at(-1)?.description }}</p><span class="card-link">View revisions →</span></a> }</div> }</main>`, styleUrl: './persona-pages.component.css' })
export class PersonaListPageComponent { readonly store = inject(PersonaStore); }

@Component({ selector: 'aura-persona-detail-page', standalone: true, imports: [DatePipe, FormsModule, RouterLink], changeDetection: ChangeDetectionStrategy.OnPush, template: `
  @if (persona(); as current) { <main class="feature-page detail-page"><a class="back-link" routerLink="/personas">← Personas</a><header class="feature-heading"><div><p class="eyebrow">Persona configuration</p><h1>{{ current.displayName }}</h1><p class="lede">{{ current.status === 'active' ? 'Available to new agent revisions.' : 'Disabled for new revisions; existing agents remain intact.' }}</p></div><button class="secondary-button" type="button" (click)="store.setStatus(current.id, current.status === 'active' ? 'disabled' : 'active')">{{ current.status === 'active' ? 'Disable persona' : 'Enable persona' }}</button></header>@if (store.notice()) { <p class="notice" role="alert">{{ store.notice() }}</p> }<section class="detail-card"><div class="section-heading"><div><h2>Revision history</h2><p>Existing agent revisions keep their original persona reference.</p></div><button class="primary-button" type="button" (click)="showRevision.set(!showRevision())">{{ showRevision() ? 'Cancel' : 'Create revision' }}</button></div>@if (showRevision()) { <form class="editor" (ngSubmit)="saveRevision(current)"><label>Display name<input name="displayName" [(ngModel)]="draft.displayName" required /></label><label>Description<textarea name="description" [(ngModel)]="draft.description" required></textarea></label><label>Behavioral instructions<textarea name="instructions" [(ngModel)]="draft.behavioralInstructions" required></textarea></label><button class="primary-button" type="submit">Save immutable revision</button></form> }<ol class="revision-list">@for (revision of current.revisions; track revision.id) { <li><div><strong>{{ revision.displayName }} r{{ revision.revision }}</strong><span>{{ revision.createdAt | date:'mediumDate' }}</span></div><p>{{ revision.description }}</p><small>{{ revision.behavioralInstructions }}</small></li> }</ol></section></main> } @else { <p class="empty-state">Loading persona…</p> }`, styleUrl: './persona-pages.component.css' })
export class PersonaDetailPageComponent { private readonly route = inject(ActivatedRoute); readonly store = inject(PersonaStore); readonly persona = computed(() => this.store.find(this.route.snapshot.paramMap.get('id') ?? '')); readonly showRevision = signal(false); draft: PersonaDraft = { displayName: '', description: '', behavioralInstructions: '' }; constructor() { void this.store.loadDetail(this.route.snapshot.paramMap.get('id') ?? ''); } saveRevision(current: PersonaProfile): void { void this.store.revise(current.id, this.draft).then(() => this.showRevision.set(false)); } }

@Component({ selector: 'aura-persona-create-page', standalone: true, imports: [FormsModule, RouterLink], changeDetection: ChangeDetectionStrategy.OnPush, template: `
  <main class="feature-page detail-page"><a class="back-link" routerLink="/personas">← Personas</a><header class="feature-heading"><div><p class="eyebrow">New reusable style</p><h1>Create a persona</h1><p class="lede">Personas shape expression without changing access or execution policy.</p></div></header><form class="detail-card editor" (ngSubmit)="save()"><label>Display name<input name="displayName" [(ngModel)]="draft.displayName" required /></label><label>Description<textarea name="description" [(ngModel)]="draft.description" required></textarea></label><label>Behavioral instructions<textarea name="instructions" [(ngModel)]="draft.behavioralInstructions" required></textarea></label><div class="form-actions"><a class="secondary-button" routerLink="/personas">Cancel</a><button class="primary-button" type="submit">Create persona</button></div></form></main>`, styleUrl: './persona-pages.component.css' })
export class PersonaCreatePageComponent { readonly store = inject(PersonaStore); draft: PersonaDraft = { displayName: '', description: '', behavioralInstructions: '' }; save(): void { void this.store.create(this.draft); } }
