import { Injectable } from '@angular/core';
import { AuraApiClient, type AuraOperationDescriptor, type AuraOperationId, type AuraOperationInput, type AuraOperationResponse, type PersonaDetail as TransportPersonaDetail, type PersonaRevision as TransportPersonaRevision } from '@aura/aura-api-client';
import { PersonaApi, PersonaDraft, PersonaProfile, PersonaRevision } from './persona-models';

@Injectable()
export class AuraPersonaApi implements PersonaApi {
  private readonly client = new AuraApiClient(new GeneratedAuraTransport());
  private csrf = '';
  async listPersonas(): Promise<ReadonlyArray<PersonaProfile>> { await this.ensureSession(); const result = await this.client.execute('listPersonas', emptyInput()); return result.items.map((item) => this.mapDetail({ ...item, revisions: [item.currentRevision] })); }
  async getPersona(id: string): Promise<PersonaProfile> { await this.ensureSession(); return this.mapDetail(await this.client.execute('getPersona', { ...emptyInput(), path: { persona_profile_id: id } })); }
  async createPersona(draft: PersonaDraft): Promise<PersonaProfile> { await this.ensureSession(); return this.mapDetail(await this.client.execute('createPersona', { ...emptyInput(), headers: this.mutationHeaders(), body: { displayName: draft.displayName, description: draft.description, instructions: draft.behavioralInstructions } })); }
  async createRevision(id: string, draft: PersonaDraft, expectedVersion: number): Promise<PersonaProfile> { await this.ensureSession(); return this.mapDetail(await this.client.execute('createPersonaRevision', { ...emptyInput(), path: { persona_profile_id: id }, headers: this.mutationHeaders(), body: { displayName: draft.displayName, description: draft.description, instructions: draft.behavioralInstructions, expectedVersion } })); }
  async setStatus(id: string, status: 'active' | 'disabled', expectedVersion: number): Promise<PersonaProfile> { await this.ensureSession(); return this.mapDetail(await this.client.execute('updatePersonaStatus', { ...emptyInput(), path: { persona_profile_id: id }, headers: this.mutationHeaders(), body: { status, expectedVersion } })); }
  private async ensureSession(): Promise<void> { if (this.csrf) return; this.csrf = (await this.client.execute('getSession', emptyInput())).csrfToken; }
  private mutationHeaders(): { readonly 'X-CSRF-Token': string; readonly 'Idempotency-Key': string } { return { 'X-CSRF-Token': this.csrf, 'Idempotency-Key': randomKey() }; }
  private mapDetail(detail: TransportPersonaDetail): PersonaProfile { return { id: detail.id, displayName: detail.currentRevision.displayName, status: detail.status, version: detail.version, currentRevisionId: detail.currentRevision.id, revisions: detail.revisions.map((revision) => this.mapRevision(revision, detail.status)) }; }
  private mapRevision(revision: TransportPersonaRevision, status: 'active' | 'disabled'): PersonaRevision { return { id: revision.id, profileId: revision.profileId, revision: revision.revision, displayName: revision.displayName, description: revision.description, behavioralInstructions: revision.instructions, status, createdAt: revision.createdAt }; }
}
function emptyInput(): { path: Record<string, never>; query: Record<string, never>; headers: Record<string, never>; body: never } { return { path: {}, query: {}, headers: {}, body: undefined as never }; }
function randomKey(): string { return typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : `aura-${Date.now()}-${Math.random().toString(36).slice(2)}`; }
class GeneratedAuraTransport { async execute<K extends AuraOperationId>(descriptor: AuraOperationDescriptor, input: AuraOperationInput<K>): Promise<AuraOperationResponse<K>> { let path = descriptor.pathTemplate; for (const [name, value] of Object.entries(input.path)) path = path.replace(`{${name}}`, encodeURIComponent(value as string)); const response = await fetch(path, { method: descriptor.method, credentials: 'include', headers: { Accept: 'application/json', ...(input.body !== undefined ? { 'Content-Type': 'application/json' } : {}), ...input.headers }, body: input.body === undefined ? undefined : JSON.stringify(input.body) }); if (!response.ok) throw new Error(response.status === 401 ? 'Sign in to manage personas.' : 'We could not complete that configuration change.'); return response.status === 204 ? undefined as AuraOperationResponse<K> : await response.json() as AuraOperationResponse<K>; } }
