"""Public persona persistence/application port."""

from typing import Protocol

# ruff: noqa: E501
from uuid import UUID

from .public import ConfigurationStatus, PersonaProfile, PersonaRevision


class PersonaConfigurationPort(Protocol):
    async def refresh(self) -> None: ...
    async def list_personas(self) -> list[PersonaProfile]: ...
    async def get_persona(self, identifier: UUID) -> PersonaProfile: ...
    async def require_active_revision(self, identifier: UUID) -> PersonaRevision: ...
    async def require_active_revision_in_transaction(
        self, session: object, identifier: UUID
    ) -> PersonaRevision: ...
    async def create_persona(self, issuer: str, subject: str, slug: str, display_name: str, description: str, instructions: str, key: str) -> PersonaProfile: ...
    async def revise_persona(self, issuer: str, subject: str, identifier: UUID, expected: int, display_name: str, description: str, instructions: str, key: str) -> PersonaProfile: ...
    async def set_status(self, issuer: str, subject: str, identifier: UUID, expected: int, status: ConfigurationStatus, key: str) -> PersonaProfile: ...
