"""Public conversation commands, queries, DTOs, and errors."""

from aura_core.domains.interaction.conversations.context import build_context
from aura_core.domains.interaction.conversations.dto import (
    AgentAssignment,
    AssignmentReason,
    Conversation,
    ConversationArchiveState,
    ConversationListFilters,
    Message,
    MessageRole,
    MessageState,
    PendingTitle,
    PersonaAssignment,
    PersonaAssignmentReason,
    PersonaAssignmentSource,
    SeededAgent,
    TitleState,
    now,
)
from aura_core.domains.interaction.conversations.repository import (
    ConversationRecord,
    SqlConversationRepository,
)
from aura_core.domains.interaction.conversations.store import (
    GENERAL_AGENT,
    ActiveRunConflict,
    AgentSwitchConfirmationRequired,
    AgentUnavailable,
    ArchivedConversationConflict,
    ConversationNotFound,
    ConversationStore,
    IdempotencyConflict,
    InvalidConversationCursor,
    InvalidConversationMetadata,
    ModelUnavailable,
    PersonaUnavailable,
    VersionConflict,
    decode_cursor,
    encode_cursor,
    filters_fingerprint,
)
from aura_core.domains.interaction.conversations.titles import (
    TITLE_SYSTEM_PROMPT,
    fallback_title_candidate,
    normalize_generated_title,
    pending_title_for,
    title_request_messages,
    validate_manual_title,
)

__all__ = [
    "GENERAL_AGENT",
    "AgentAssignment",
    "AssignmentReason",
    "PersonaAssignment",
    "PersonaAssignmentReason",
    "PersonaAssignmentSource",
    "PendingTitle",
    "TitleState",
    "ActiveRunConflict",
    "AgentSwitchConfirmationRequired",
    "AgentUnavailable",
    "PersonaUnavailable",
    "Conversation",
    "ConversationArchiveState",
    "ConversationListFilters",
    "ConversationNotFound",
    "ConversationRecord",
    "ConversationStore",
    "ArchivedConversationConflict",
    "IdempotencyConflict",
    "InvalidConversationCursor",
    "InvalidConversationMetadata",
    "Message",
    "MessageRole",
    "MessageState",
    "ModelUnavailable",
    "SeededAgent",
    "SqlConversationRepository",
    "VersionConflict",
    "decode_cursor",
    "encode_cursor",
    "filters_fingerprint",
    "build_context",
    "now",
    "TITLE_SYSTEM_PROMPT",
    "fallback_title_candidate",
    "normalize_generated_title",
    "pending_title_for",
    "title_request_messages",
    "validate_manual_title",
]
